version: '3.7'

services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db
    networks:
      - sneaker-network

  web:
    image: jasonzza/node-sneaker
    restart: always
    environment:
      - NODE_ENV: production
    depends_on:
      - database
    ports:
      - 4455:4455
    networks:
      - sneaker-network

networks:
  sneaker-network:
    driver: bridge
