version: '3.7'

services:
  database:
    image: mongo
    restart: always
    volumes:
      - ~/data/db:/data/db

  web:
    image: jasonzza/node-sneaker
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./variables.env:/app/variables.env
    depends_on:
      - database
    ports:
      - 4455:4455
